# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

  
image:
  repository: ripa1986/golangdemo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imageConfig:
  pullPolicy: IfNotPresent
imagePullSecrets: [name: ra-creg]

config:
  enabled: true
  configmap: ra-user-operator-configmap
  path: "/app/config"


securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  capabilities:
    drop: ["AUDIT_WRITE","SYS_CHROOT"]

podSecurityContext: {}

nodeSelector:
  "kubernetes.io/os": linux
affinity:
  nodeAffinity:     
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: kubernetes.azure.com/agentpool
          operator: NotIn
          values:
          - linuxnpwks

